export const GRID_SIZE = 6;
export enum SHIP_TYPE {
  CARRIER,
  BATTLESHIP,
  CRUISER,
  SUBMARINE,
}

export const SHIP_SIZE: Record<SHIP_TYPE, number> = {
  [SHIP_TYPE.CARRIER]: 4,
  [SHIP_TYPE.BATTLESHIP]: 3,
  [SHIP_TYPE.CRUISER]: 2,
  [SHIP_TYPE.SUBMARINE]: 2,
};

export const TOTAL_SHIPS =
  SHIP_SIZE[SHIP_TYPE.CARRIER] +
  SHIP_SIZE[SHIP_TYPE.BATTLESHIP] +
  SHIP_SIZE[SHIP_TYPE.CRUISER] +
  SHIP_SIZE[SHIP_TYPE.SUBMARINE];
